-- Fix for profiles and candidates tables (current_role is reserved keyword)

-- Drop and recreate profiles table with quoted current_role
DROP TABLE IF EXISTS profiles CASCADE;

CREATE TABLE profiles (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  title text NOT NULL,
  location text NOT NULL,
  education text,
  portfolio text,
  mobile text,
  whatsapp text,
  primary_email text,
  secondary_email text,
  current_location text,
  preferred_location text,
  date_of_birth text,
  gender text,
  portfolio_url text,
  website_url text,
  linkedin_url text,
  profile_picture text,
  banner_image text,
  resume_file text,
  resume_text text,
  applied_jobs_count text DEFAULT '0',
  highest_qualification text,
  college_name text,
  skills text,
  pedigree_level text,
  notice_period text,
  current_company text,
  "current_role" text,
  current_domain text,
  company_level text,
  product_service text
);

-- Drop and recreate candidates table with quoted current_role
DROP TABLE IF EXISTS candidates CASCADE;

CREATE TABLE candidates (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id text NOT NULL UNIQUE,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  password text,
  google_id text UNIQUE,
  phone text,
  company text,
  designation text,
  age text,
  gender text,
  location text,
  experience text,
  skills text,
  profile_picture text,
  banner_image text,
  resume_file text,
  resume_text text,
  education text,
  "current_role" text,
  portfolio_url text,
  website_url text,
  linkedin_url text,
  pipeline_status text DEFAULT 'New',
  added_by text,
  assigned_to text,
  ctc text,
  ectc text,
  notice_period text,
  position text,
  pedigree_level text,
  company_level text,
  company_sector text,
  product_service text,
  product_category text,
  product_domain text,
  employment_type text,
  is_active boolean DEFAULT true,
  is_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  created_at text NOT NULL,
  last_viewed_at text
);

