services:
  - type: web
    name: job-portal-backend
    env: node
    plan: starter
    buildCommand: npm run build:backend
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: staffos-db
          property: connectionString

databases:
  - name: staffos-db
    databaseName: staffos
    user: staffos_user
    plan: starter